/* deadpeak/istruzioni.js — COME SI GIOCA A DEAD PEAK (19/09/2026, regole nuove)
   UNA SOLA FONTE per il pannello COME SI GIOCA (lobby e attesa del tavolo). La pagina lo scarica solo quando si apre
   il pannello; le clip (deadpeak/clip/*.mp4, 400x400, 2-4 s, senza audio) partono solo quando si vedono.
   Le regole sono quelle del motore sul server (climb2_rt.py 20260919b): se cambia una regola, si cambia QUI.
   Campi di una voce: k chiave, ic emoji, c clip (nome del file senza .mp4, facoltativo), it/en: t titolo, x testo.
   Oggetti: id, img (deadpeak/icone/<img>.webp, le icone del gioco), usi, ic (emoji di riserva), c, it/en. */
/* DP CLIP 19/09: clip rifatte (chi agisce e chi subisce nel quadro; piazzamento e uso): rampino_2, muro_oggetto_2, piccozza_2, masso_2, catena_2, scala_2, colla_2, petardo_2, trampolino_2, sapone_2 */
var DP_ISTR = {
  ver: "20260919b",
  ui: {
    it: { hd: "🗼 DEAD PEAK — COME SI GIOCA", chiudi: "✖ CHIUDI", usi: "USI", carica: "Carico le istruzioni…",
          tab: { r: "📜 REGOLE", c: "🕹️ COMANDI", i: "🎒 OGGETTI", s: "💰 SOLDI" } },
    en: { hd: "🗼 DEAD PEAK — HOW TO PLAY", chiudi: "✖ CLOSE", usi: "USES", carica: "Loading the instructions…",
          tab: { r: "📜 RULES", c: "🕹️ CONTROLS", i: "🎒 ITEMS", s: "💰 MONEY" } }
  },

  regole: [
    { k: "vetta", ic: "🏁", c: "vetta",
      it: { t: "PRIMO IN VETTA, PIGLIA TUTTO",
            x: "Una torre di 8 stanze, diversa a ogni partita. Chi tocca per primo il caveau in cima vince il piatto: tutti vedono la scena del vincitore, col suo nome grande, e poi la classifica." },
      en: { t: "FIRST TO THE TOP TAKES ALL",
            x: "A tower of 8 rooms, different every match. The first to touch the vault at the top wins the pot: everyone sees the winner’s scene, with their name in big letters, then the standings." } },
    { k: "pari", ic: "🤝",
      it: { t: "ARRIVATI INSIEME",
            x: "Se due o più toccano la vetta nello stesso istante è pari: il piatto si divide in parti uguali fra loro. Nei tornei la partita si rigioca." },
      en: { t: "ARRIVING TOGETHER",
            x: "If two or more touch the top at the same instant it is a tie: the pot is split equally among them. In tournaments the match is replayed." } },
    { k: "morte", ic: "☠️", c: "gancio",
      it: { t: "SI MUORE, SI RIPARTE",
            x: "Seghe, presse, laser, fuoco, mine e missili uccidono al tocco. In meno di un secondo rinasci al gancio della stanza, la lucina verde (o al tuo CHIODO, se ne hai piantato uno)." },
      en: { t: "YOU DIE, YOU RESTART",
            x: "Saws, presses, lasers, fire, mines and missiles kill on touch. In under a second you respawn at the room’s hook, the green light (or at your PITON, if you planted one)." } },
    { k: "trappole", ic: "⏱️", c: "trappola",
      it: { t: "LE TRAPPOLE HANNO UN RITMO",
            x: "Ogni stanza ripete il suo ritmo: guarda un giro dal gancio e parti nel momento giusto. Ogni trappola avvisa prima di colpire." },
      en: { t: "TRAPS HAVE A RHYTHM",
            x: "Every room repeats its beat: watch one loop from the hook and go at the right moment. Every trap warns before it strikes." } },
    { k: "vie", ic: "🛣️",
      it: { t: "TRE VIE PER STANZA",
            x: "Ogni stanza ha una via SICURA (lenta), una VELOCE dentro il pericolo e una ESPERTA o da OGGETTO: la cassa dell’oggetto giusto sta in un punto che costa." },
      en: { t: "THREE ROUTES PER ROOM",
            x: "Every room has a SAFE route (slow), a FAST one through the danger and an EXPERT or ITEM one: the crate with the right item sits somewhere risky." } },
    { k: "lava", ic: "🌋", c: "lava",
      it: { t: "LA LAVA PARTE A 2 MINUTI",
            x: "Dopo 2 minuti dal VIA (dieci secondi prima compare l’avviso) la lava sale dal fondo, piano, e arriva in cima verso i 3 minuti e mezzo. Se ti prende, o copre il tuo gancio, sei FUORI per sempre: niente rinascita, guardi la gara fino alla fine (◀ ▶ per cambiare chi segui)." },
      en: { t: "THE LAVA STARTS AT 2 MINUTES",
            x: "2 minutes after GO (a warning appears ten seconds before) the lava rises from the bottom, slowly, reaching the top at about 3 and a half minutes. If it catches you, or covers your hook, you are OUT for good: no respawn, you watch the race to the end (◀ ▶ to switch who you follow)." } },
    { k: "ultimo", ic: "🔥",
      it: { t: "SE LA LAVA PRENDE TUTTI",
            x: "Vince l’ultimo a uscire. Se escono nello stesso istante vince chi stava più in alto; alla stessa altezza è pari e il piatto si divide. Quando resta un solo giocatore in gara, ha vinto lui." },
      en: { t: "IF THE LAVA TAKES EVERYONE",
            x: "The last one out wins. If they go out at the same instant, whoever was higher wins; at the same height it is a tie and the pot is split. When only one player is left in the race, they win." } },
    { k: "sangue", ic: "🩸",
      it: { t: "SANGUE",
            x: "Tasto in alto: ALTO, MEDIO o NIENTE. Nelle partite con più di 7 giocatori parte da MEDIO e chi ti passa sopra diventa trasparente." },
      en: { t: "BLOOD",
            x: "Top button: HIGH, MEDIUM or NONE. In matches with more than 7 players it starts at MEDIUM and whoever is on top of you turns see-through." } }
  ],

  comandi: [
    { k: "salto", ic: "🕹️", c: "salto",
      it: { t: "LEVETTA E SALTO",
            x: "Levetta a sinistra per correre. SALTO a destra: un tocco è un saltello, tenuto è il salto alto (fino a 3 righe e mezzo). In aria la levetta ti sposta ancora." },
      en: { t: "STICK AND JUMP",
            x: "Stick on the left to run. JUMP on the right: a tap is a hop, holding it is the high jump (up to 3 and a half rows). In the air the stick still steers you." } },
    { k: "muro", ic: "🧱", c: "muro",
      it: { t: "IL MURO È IL TUO SALTO",
            x: "Salta contro un muro e rimbalzi via dall’altra parte. Fra due muri vicini (un camino) si sale velocissimi, da un muro all’altro; sullo stesso muro si sale piano." },
      en: { t: "WALLS ARE YOUR JUMP",
            x: "Jump into a wall and you bounce off the other way. Between two close walls (a chimney) you climb very fast, wall to wall; on the same wall you climb slowly." } },
    { k: "spinta", ic: "💥", c: "spinta",
      it: { t: "LA SPINTA A MANI VUOTE",
            x: "Il tasto tondo, senza oggetti in mano, è uno scatto che sbalza chi colpisci. Correndo a tutta velocità contro un rivale lo spalli via. 5 secondi di tregua al VIA e 2 dopo ogni rinascita." },
      en: { t: "THE EMPTY-HANDED SHOVE",
            x: "The round button, with no item in hand, is a dash that knocks away whoever you hit. Running full speed into a rival bumps them away. 5 seconds of truce at GO and 2 after each respawn." } },
    { k: "oggetto", ic: "🎒",
      it: { t: "UN OGGETTO ALLA VOLTA",
            x: "Passa su una cassa: l’oggetto che galleggia sopra è tuo (finché ne hai uno non ne prendi altri). Il tasto tondo lo usa subito; la levetta in quel momento sceglie la direzione. Morendo lo perdi." },
      en: { t: "ONE ITEM AT A TIME",
            x: "Run over a crate: the item floating above it is yours (while you hold one you can’t take another). The round button uses it at once; the stick at that moment picks the direction. Dying loses it." } }
  ],

  oggetti: [
    { id: 1, img: "rampino", ic: "🪝", usi: 2, c: "rampino_2",
      it: { t: "RAMPINO", x: "Voli all’anello d’oro a tiro (in alto davanti se non miri). Senza anello tira giù un rivale." },
      en: { t: "GRAPPLE", x: "You fly to a golden ring in range (up and forward if you don’t aim). With no ring it pulls a rival down." } },
    { id: 2, img: "chiodo", ic: "📌", usi: 1, c: "chiodo",
      it: { t: "CHIODO", x: "Piantalo coi piedi a terra: alla prossima morte rinasci lì. Una piccozza lo spacca, la lava lo copre." },
      en: { t: "PITON", x: "Plant it with your feet on the ground: your next death respawns you there. A pickaxe breaks it, the lava covers it." } },
    { id: 3, img: "muro", ic: "🧱", usi: 1, c: "muro_oggetto_2",
      it: { t: "MURO", x: "Colonna di 3 blocchi davanti a te (per il salto a muro o per chiudere la strada). Levetta giù = ponte di 3. Dura 8 secondi." },
      en: { t: "WALL", x: "A 3-block column in front of you (to wall-jump or to block the way). Stick down = a 3-block bridge. Lasts 8 seconds." } },
    { id: 4, img: "piccozza", ic: "⛏️", usi: 2, c: "piccozza_2",
      it: { t: "PICCOZZA", x: "Fendente davanti: sbalza i rivali e spacca le pareti crepate, cioè i passaggi segreti." },
      en: { t: "PICKAXE", x: "A swing in front: knocks rivals away and breaks cracked walls, which are the secret passages." } },
    { id: 5, img: "masso", ic: "🪨", usi: 1, c: "masso_2",
      it: { t: "MASSO", x: "Rotola, rimbalza, cade dalle porte: travolge chi sta sotto e fa scoppiare le mine." },
      en: { t: "BOULDER", x: "Rolls, bounces, drops through doors: bowls over whoever is below and sets off mines." } },
    { id: 6, img: "magnesite", ic: "✨", usi: 1, c: "magnesite",
      it: { t: "MAGNESITE", x: "Salto più alto per 5 secondi: arrivi sui ripiani alti 4." },
      en: { t: "CHALK", x: "Higher jump for 5 seconds: you reach 4-high ledges." } },
    { id: 7, img: "catena", ic: "⛓️", usi: 2, c: "catena_2",
      it: { t: "CATENA", x: "Incatena un rivale davanti a te per un secondo e mezzo (lui pigia SALTO per liberarsi). Se va a vuoto l’uso torna." },
      en: { t: "CHAIN", x: "Chains a rival ahead of you for a second and a half (they mash JUMP to break free). If it misses, you get the use back." } },
    { id: 8, img: "scala", ic: "🪜", usi: 1, c: "scala_2",
      it: { t: "SCALA", x: "Tre pioli sopra di te, uno ogni due righe: si sale saltando. Durano 20 secondi e valgono per tutti." },
      en: { t: "LADDER", x: "Three rungs above you, one every two rows: you climb by jumping. They last 20 seconds and anyone can use them." } },
    { id: 9, img: "colla", ic: "🍯", usi: 1, c: "colla_2",
      it: { t: "COLLA", x: "Chiazza dietro di te: chi ci passa va piano per un secondo." },
      en: { t: "GLUE", x: "A puddle behind you: whoever steps in slows down for a second." } },
    { id: 10, img: "petardo", ic: "🧨", usi: 1, c: "petardo_2",
      it: { t: "PETARDO", x: "Mina dietro di te: chi la calpesta la accende e viene sbalzato." },
      en: { t: "FIRECRACKER", x: "A mine behind you: whoever steps on it lights it and gets blasted." } },
    { id: 11, img: "trampolino", ic: "🛎️", usi: 1, c: "trampolino_2",
      it: { t: "TRAMPOLINO", x: "Pedana davanti a te: rimbalzo fisso di 5 celle, per tutti." },
      en: { t: "TRAMPOLINE", x: "A pad in front of you: a fixed 5-cell bounce, for everyone." } },
    { id: 12, img: "sapone", ic: "🧼", usi: 1, c: "sapone_2",
      it: { t: "SAPONE", x: "Lastra dietro di te: chi ci corre sopra non riesce a frenare." },
      en: { t: "SOAP", x: "A slick behind you: whoever runs on it can’t brake." } }
  ],

  soldi: [
    { k: "piatto", ic: "💰",
      it: { t: "IL PIATTO",
            x: "Tutti mettono la stessa posta; la casa tiene l’8% e il resto va al vincitore (diviso in parti uguali se è pari). Se la torre non passa il controllo all’inizio, la partita si annulla e le poste tornano a tutti." },
      en: { t: "THE POT",
            x: "Everyone puts in the same stake; the house keeps 8% and the rest goes to the winner (split equally on a tie). If the tower fails its check at the start, the match is cancelled and everyone gets their stake back." } },
    { k: "esci", ic: "📴",
      it: { t: "SE ESCI O CADE LA RETE",
            x: "Il tuo scalatore resta in gara fermo, e la lava prima o poi lo porta fuori. Se rientri in tempo riprendi a correre da dove sei." },
      en: { t: "IF YOU LEAVE OR LOSE SIGNAL",
            x: "Your climber stays in the race, standing still, and sooner or later the lava takes them out. If you come back in time you carry on from where you are." } },
    { k: "allena", ic: "🤖",
      it: { t: "ALLENATI COI BOT",
            x: "Gratis, contro 4 bot. Alla prima partita i bot vanno piano (in cima verso i 2 minuti e un quarto) e non ti attaccano. Se vinci, la volta dopo sono più svelti (4 livelli, poi i bot veri); se perdi, tornano più lenti." },
      en: { t: "PRACTICE WITH BOTS",
            x: "Free, against 4 bots. In your first match the bots go slowly (reaching the top at about 2 and a quarter minutes) and don’t attack you. Win and next time they are faster (4 levels, then the real bots); lose and they slow down again." } },
    { k: "tornei", ic: "🏆",
      it: { t: "TORNEI",
            x: "Niente soldi in gioco nella partita: passa il turno chi arriva primo. Un pari si rigioca. Gli altri possono guardare da spettatori." },
      en: { t: "TOURNAMENTS",
            x: "No money on the match itself: whoever arrives first goes through. A tie is replayed. Others can watch as spectators." } }
  ]
};
