/* lastcall/istruzioni.js — COME SI GIOCA A LAST CALL (14/09/2026)
   UNA SOLA FONTE per il pannello della lobby (index.html) e per quello dentro
   il tavolo (lastcall.html). Ogni spiegazione e' stata controllata sul motore
   che gira sul server (lastcall_rt.py = _lc_regole.js): se cambia una regola,
   si cambia QUI.
   ⚠️ Solo virgolette doppie per le stringhe; l'apostrofo e' quello tipografico.
   Campi di una carta: id (= nome del file .webp), f (famiglia),
   it/en: n nome · q quando si gioca · x cosa fa · o occhio (facoltativo). */
var LC_ISTR = {
  fam: [
    { k: "comando", it: "LE TRE CHE COMANDANO", en: "THE THREE IN CHARGE",
      sit: "Non si giocano: decidono chi resta e chi esce.",
      sen: "You never play these: they decide who stays and who goes." },
    { k: "turno", it: "IL TURNO", en: "THE TURN",
      sit: "Cambiano chi pesca e quante volte.",
      sen: "They change who draws, and how many times." },
    { k: "mazzo", it: "IL MAZZO", en: "THE DECK",
      sit: "Guardano, spostano e rimescolano le carte del mazzo.",
      sen: "They look at, move and reshuffle the cards in the deck." },
    { k: "persone", it: "LE PERSONE", en: "THE PEOPLE",
      sit: "Colpiscono un altro giocatore, o proteggono te.",
      sen: "They hit another player, or protect you." },
    { k: "gettoni", it: "I GETTONI", en: "THE CHIPS",
      sit: "Da soli non valgono niente: si giocano a coppie o a tris per rubare.",
      sen: "Worthless alone: you play them in pairs or threes to steal." }
  ],

  carte: [
    /* ── LE TRE CHE COMANDANO ─────────────────────────────────────── */
    { id: "buttafuori", f: "comando",
      it: { n: "IL BUTTAFUORI", q: "NON SI GIOCA · ARRIVA DAL MAZZO",
            x: "Nel mazzo ce ne sono tanti quanti siete meno uno. Quando lo peschi, o lo rubi a un altro coi gettoni, succede la prima di queste cose: se hai il SANGUE FREDDO lo tieni in mano e resti al tavolo; se hai una MAZZETTA la usi e lo rimetti nel mazzo dove vuoi; se non hai niente, sei fuori.",
            o: "Accanto al mazzo il segnalino dei buttafuori ti dice quanti sono ancora in gioco. Se al tavolo non ne resta nessuno nel mazzo ma qualcuno ne tiene uno col sangue freddo, ne entra uno nuovo: qualcuno esce sempre." },
      en: { n: "THE BOUNCER", q: "NOT PLAYED · COMES FROM THE DECK",
            x: "The deck holds one fewer than there are players. When you draw one, or steal one from another player with chips, the first of these happens: if you hold COOL HAND you keep it and stay at the table; if you hold a BRIBE you spend it and slide the bouncer back into the deck wherever you want; if you have neither, you are out.",
            o: "The bouncer counter next to the deck tells you how many are still in play. If none is left in the deck but someone is holding one with cool hand, a new one comes in: somebody always leaves." } },
    { id: "bancarotta", f: "comando",
      it: { n: "BANCAROTTA", q: "NON SI GIOCA · ARRIVA DAL MAZZO",
            x: "Nel mazzo ce n’è al massimo una. La prima volta che qualcuno la pesca non esce: la rimette nel mazzo nel punto che sceglie, ma a faccia in su. Da quel momento tutti vedono dove sta. La seconda volta che viene pescata, chi la pesca è fuori: non la ferma né la MAZZETTA né il SANGUE FREDDO.",
            o: "Quando è in cima al mazzo si vede la scritta IN CIMA: se tocca a te, non pescare. Usa DAL FONDO, PASSO, IMPILA o fai pescare un altro." },
      en: { n: "BUST", q: "NOT PLAYED · COMES FROM THE DECK",
            x: "There is at most one in the deck. The first time someone draws it, they are not out: they slide it back into the deck wherever they choose, but face up. From then on everyone can see where it is. The second time it is drawn, whoever draws it is out: neither a BRIBE nor COOL HAND can stop it.",
            o: "When it sits on top of the deck it says ON TOP: if it is your turn, do not draw. Use FROM THE BOTTOM, CHECK, STACK, or make someone else draw." } },
    { id: "mazzetta", f: "comando",
      it: { n: "LA MAZZETTA", q: "NON SI GIOCA · SCATTA QUANDO TI ARRIVA UN BUTTAFUORI",
            x: "Ognuno ne riceve una all’inizio, e altre possono uscire dal mazzo. Quando peschi un buttafuori, o ne rubi uno coi gettoni, la spendi e resti al tavolo: poi scegli in che punto del mazzo rimetterlo, in cima, in fondo o in mezzo. Gli altri vedono che lo hai rimesso, ma non dove. Se lo avevi pescato il turno finisce lì; se lo avevi rubato, il turno continua.",
            o: "Se il tempo per scegliere scade, il buttafuori finisce in un punto a caso. Metterlo in cima quando tocca al prossimo è il colpo più cattivo del gioco." },
      en: { n: "THE BRIBE", q: "NOT PLAYED · TRIGGERS WHEN A BOUNCER COMES TO YOU",
            x: "Everyone starts with one, and more can turn up in the deck. When you draw a bouncer, or steal one with chips, you spend it and stay at the table: then you choose where in the deck the bouncer goes back, on top, at the bottom or in the middle. The others see that you put it back, but not where. If you drew it your turn ends there; if you stole it, your turn goes on.",
            o: "If your time to choose runs out, the bouncer goes to a random spot. Putting it on top right before the next player draws is the nastiest move in the game." } },

    /* ── IL TURNO ─────────────────────────────────────────────────── */
    { id: "non_vale", f: "turno",
      it: { n: "NON VALE", q: "ANCHE FUORI TURNO · SULLA CARTA DI UN ALTRO",
            x: "Annulla la carta che un altro ha appena giocato: è come se non fosse mai successa, ma la carta resta spesa. Quando qualcuno gioca, chi ha un NON VALE vede l’anello e ha 3 secondi per calarlo, 5 se la carta colpiva proprio lui. Anche un NON VALE si può annullare con un altro NON VALE: se ne calano due, la carta vale di nuovo.",
            o: "Non ferma le pescate, la MAZZETTA e i furti coi gettoni. Chi ha giocato la carta annullata continua il suo turno." },
      en: { n: "NO DICE", q: "EVEN OUT OF TURN · ON SOMEONE ELSE’S CARD",
            x: "Cancels the card someone just played: as if it never happened, but the card stays spent. When someone plays, whoever holds a NO DICE sees the ring and has 3 seconds to drop it, 5 if the card was aimed at them. A NO DICE can itself be cancelled by another NO DICE: if two are dropped, the card counts again.",
            o: "It does not stop draws, the BRIBE or chip steals. Whoever played the cancelled card carries on with their turn." } },
    { id: "passo", f: "turno",
      it: { n: "PASSO", q: "NEL TUO TURNO · NON PESCHI",
            x: "Chiudi il turno senza toccare il mazzo. Il gioco passa al prossimo.",
            o: "Se dovevi fare più turni di fila (PAGO IO, PAGA TU, RADDOPPIO), ne salta uno solo." },
      en: { n: "CHECK", q: "ON YOUR TURN · YOU DON’T DRAW",
            x: "You end your turn without touching the deck. Play moves to the next player.",
            o: "If you owed several turns in a row (MY ROUND, YOUR ROUND, DOUBLE DOWN), it skips just one of them." } },
    { id: "raddoppio", f: "turno",
      it: { n: "RADDOPPIO", q: "NEL TUO TURNO · NON PESCHI",
            x: "Non peschi, e il prossimo deve fare due turni di fila. Se dovevi ancora dei turni, passano a lui tutti, più uno. Se anche lui gioca RADDOPPIO, il conto si somma e va avanti al giocatore dopo.",
            o: "È la carta per scaricare il pericolo quando sai che in cima c’è un buttafuori." },
      en: { n: "DOUBLE DOWN", q: "ON YOUR TURN · YOU DON’T DRAW",
            x: "You don’t draw, and the next player must take two turns in a row. If you still owed turns, all of them pass to them, plus one. If they play DOUBLE DOWN too, the tab stacks and moves on to the player after.",
            o: "This is the card to dump the danger when you know a bouncer is on top." } },
    { id: "ultimo_ordine", f: "turno",
      it: { n: "ULTIMO ORDINE", q: "NEL TUO TURNO · NON PESCHI",
            x: "Non peschi, e tutti i turni che dovevi ancora fare si cancellano insieme a questo. Il gioco passa al prossimo.",
            o: "La difesa contro RADDOPPIO, PAGA TU e PAGO IO: un solo gesto ti toglie tutto il conto." },
      en: { n: "LAST ORDERS", q: "ON YOUR TURN · YOU DON’T DRAW",
            x: "You don’t draw, and every turn you still owed is wiped out along with this one. Play moves to the next player.",
            o: "The answer to DOUBLE DOWN, YOUR ROUND and MY ROUND: one move clears your whole tab." } },
    { id: "pago_io", f: "turno",
      it: { n: "PAGO IO", q: "NEL TUO TURNO · NON PESCHI ORA",
            x: "Questo turno lo chiudi senza pescare, ma poi ne fai altri due di fila. Se nel frattempo giochi RADDOPPIO o PAGA TU, i turni che ti restavano passano all’altro insieme al resto.",
            o: "Serve a comprare tempo, oppure a caricare un RADDOPPIO: più turni hai in sospeso, più ne arrivano al prossimo." },
      en: { n: "MY ROUND", q: "ON YOUR TURN · NO DRAW NOW",
            x: "You end this turn without drawing, but then you take two more in a row. If meanwhile you play DOUBLE DOWN or YOUR ROUND, the turns you had left go to the other player along with the rest.",
            o: "Use it to buy time, or to load up a DOUBLE DOWN: the more turns you owe, the more land on the next player." } },
    { id: "paga_tu", f: "turno",
      it: { n: "PAGA TU", q: "NEL TUO TURNO · SCEGLI UN GIOCATORE · NON PESCHI",
            x: "Scegli un giocatore: il turno passa a lui, anche se non era il prossimo, e deve fare due turni di fila. Se dovevi ancora dei turni, gli arrivano anche quelli. Il giro poi riparte da lui.",
            o: "Come RADDOPPIO, ma decidi tu chi paga." },
      en: { n: "YOUR ROUND", q: "ON YOUR TURN · PICK A PLAYER · YOU DON’T DRAW",
            x: "Pick a player: the turn goes to them, even if they were not next, and they must take two turns in a row. If you still owed turns, those go to them too. Play then carries on from them.",
            o: "Like DOUBLE DOWN, but you choose who pays." } },
    { id: "contromano", f: "turno",
      it: { n: "CONTROMANO", q: "NEL TUO TURNO · NON PESCHI",
            x: "Il giro cambia senso e il tuo turno finisce senza pescare. Chi prima veniva dopo di te adesso aspetta, e tocca a chi c’era prima.",
            o: "In due al tavolo funziona come un PASSO." },
      en: { n: "WRONG WAY", q: "ON YOUR TURN · YOU DON’T DRAW",
            x: "The direction of play flips and your turn ends without drawing. The player who used to follow you now waits, and the one before you goes next.",
            o: "With only two at the table it works like a CHECK." } },

    /* ── IL MAZZO ─────────────────────────────────────────────────── */
    { id: "sbircia", f: "mazzo",
      it: { n: "SBIRCIA", q: "NEL TUO TURNO · IL TURNO CONTINUA",
            x: "Guardi le prime tre carte del mazzo. Le vedi solo tu, e restano dove sono.",
            o: "Dopo averle viste puoi ancora giocare altre carte, prima di pescare." },
      en: { n: "THE PEEK", q: "ON YOUR TURN · YOUR TURN GOES ON",
            x: "You look at the top three cards of the deck. Only you see them, and they stay where they are.",
            o: "After looking you can still play more cards before you draw." } },
    { id: "sbircia_due", f: "mazzo",
      it: { n: "SBIRCIA IN DUE", q: "NEL TUO TURNO · IL TURNO CONTINUA",
            x: "Guardi le prime tre carte del mazzo, e le vede anche il giocatore che viene dopo di te. Restano dove sono.",
            o: "Sapete in due cosa c’è in cima: tienine conto prima di passargli il turno." },
      en: { n: "PEEK TOGETHER", q: "ON YOUR TURN · YOUR TURN GOES ON",
            x: "You look at the top three cards of the deck, and the player after you sees them too. They stay where they are.",
            o: "Two of you now know what is on top: keep that in mind before you hand them the turn." } },
    { id: "impila", f: "mazzo",
      it: { n: "IMPILA", q: "NEL TUO TURNO · IL TURNO CONTINUA",
            x: "Prendi le prime tre carte del mazzo, le guardi e le rimetti in cima nell’ordine che scegli tu. Nessun altro le vede.",
            o: "Se trovi un buttafuori, mettilo terzo e fai pescare gli altri; o in cima, prima di un RADDOPPIO. Se il tempo scade restano come erano." },
      en: { n: "STACK", q: "ON YOUR TURN · YOUR TURN GOES ON",
            x: "You take the top three cards of the deck, look at them and put them back on top in the order you choose. Nobody else sees them.",
            o: "Found a bouncer? Put it third and let the others draw; or on top, right before a DOUBLE DOWN. If time runs out they stay as they were." } },
    { id: "impila_due", f: "mazzo",
      it: { n: "IMPILA IN DUE", q: "NEL TUO TURNO · IL TURNO CONTINUA",
            x: "Come IMPILA: riordini le prime tre carte come vuoi. Ma il giocatore dopo di te vede l’ordine finale in cui le hai messe.",
            o: "Lui sa cosa pescherà: non puoi tendergli una trappola, puoi solo spingerlo a giocare le sue carte." },
      en: { n: "STACK & SHOW", q: "ON YOUR TURN · YOUR TURN GOES ON",
            x: "Like STACK: you reorder the top three cards however you like. But the player after you sees the final order you left them in.",
            o: "They know what they will draw: you cannot set a trap, only push them into spending their cards." } },
    { id: "dal_fondo", f: "mazzo",
      it: { n: "DAL FONDO", q: "NEL TUO TURNO · È LA TUA PESCATA",
            x: "Peschi la carta in fondo al mazzo invece di quella in cima. Conta come la pescata del turno, quindi il turno finisce. Se in fondo c’è un buttafuori, vale come sempre.",
            o: "La via di fuga quando sai che in cima c’è il pericolo, ma in fondo non ha guardato nessuno." },
      en: { n: "FROM THE BOTTOM", q: "ON YOUR TURN · IT IS YOUR DRAW",
            x: "You draw the bottom card of the deck instead of the top one. It counts as your draw for the turn, so your turn ends. If there is a bouncer at the bottom, it counts as usual.",
            o: "The escape route when you know danger is on top, but nobody has looked at the bottom." } },
    { id: "sottobanco", f: "mazzo",
      it: { n: "SOTTOBANCO", q: "NEL TUO TURNO · CHIUDE IL TURNO",
            x: "Prendi la prima carta del mazzo, la guardi solo tu e la rimetti nel mazzo nel punto che scegli. Non entra mai nella tua mano, nemmeno se è un buttafuori o la BANCAROTTA. Poi il tuo turno finisce.",
            o: "Chiudi il turno senza rischiare niente, e decidi tu dove finisce la carta. Se il tempo scade, va in un punto a caso." },
      en: { n: "UNDER THE COUNTER", q: "ON YOUR TURN · ENDS YOUR TURN",
            x: "You take the top card of the deck, only you look at it, and you slide it back into the deck wherever you choose. It never enters your hand, not even if it is a bouncer or BUST. Then your turn ends.",
            o: "You end your turn at zero risk, and you decide where that card goes. If time runs out, it goes to a random spot." } },
    { id: "primo_ultimo", f: "mazzo",
      it: { n: "PRIMO E ULTIMO", q: "NEL TUO TURNO · IL TURNO CONTINUA",
            x: "La carta in cima va in fondo e quella in fondo va in cima. Nessuno le guarda, nemmeno tu.",
            o: "Rovina il lavoro di chi ha appena fatto IMPILA o SBIRCIA." },
      en: { n: "TOP AND TAIL", q: "ON YOUR TURN · YOUR TURN GOES ON",
            x: "The top card goes to the bottom and the bottom card goes to the top. Nobody looks at them, not even you.",
            o: "It wrecks the work of whoever just played STACK or THE PEEK." } },
    { id: "rimescola", f: "mazzo",
      it: { n: "RIMESCOLA", q: "NEL TUO TURNO · IL TURNO CONTINUA",
            x: "Mescoli tutto il mazzo. Chi aveva guardato le prime carte non sa più cosa c’è.",
            o: "Se la BANCAROTTA è già scoperta si mescola anche lei, ma resta a faccia in su: tutti vedono il suo posto nuovo." },
      en: { n: "RESHUFFLE", q: "ON YOUR TURN · YOUR TURN GOES ON",
            x: "You shuffle the whole deck. Anyone who had looked at the top cards no longer knows what is there.",
            o: "If BUST is already face up it gets shuffled too, but stays face up: everyone sees its new spot." } },
    { id: "si_chiude", f: "mazzo",
      it: { n: "SI CHIUDE", q: "NEL TUO TURNO · NON PESCHI",
            x: "Nel mazzo ce n’è al massimo una. Tutti i buttafuori del mazzo vanno in cima, il resto si mescola sotto. Il tuo turno finisce senza pescare: chi viene dopo pescherà un buttafuori, e poi quello dopo ancora, uno dopo l’altro.",
            o: "Giocala quando gli altri non hanno più mazzette. Un NON VALE la può fermare." },
      en: { n: "CLOSING TIME", q: "ON YOUR TURN · YOU DON’T DRAW",
            x: "There is at most one in the deck. Every bouncer in the deck goes on top, and the rest is shuffled underneath. Your turn ends without drawing: the next player will draw a bouncer, then the one after, one after another.",
            o: "Play it when the others are out of bribes. A NO DICE can stop it." } },

    /* ── LE PERSONE ───────────────────────────────────────────────── */
    { id: "segnato", f: "persone",
      it: { n: "SEGNATO", q: "NEL TUO TURNO · SCEGLI UN GIOCATORE · IL TURNO CONTINUA",
            x: "Scegli un giocatore: una carta a caso della sua mano resta scoperta, e tutto il tavolo la vede. Lui può ancora giocarla, ma adesso tutti sanno che ce l’ha.",
            o: "Tocca la carta scoperta sulla sua targa per leggerla. Utile prima di un furto coi gettoni." },
      en: { n: "MARKED", q: "ON YOUR TURN · PICK A PLAYER · YOUR TURN GOES ON",
            x: "Pick a player: a random card from their hand stays face up, and the whole table sees it. They can still play it, but now everyone knows they hold it.",
            o: "Tap the face-up card on their nameplate to read it. Handy before a chip steal." } },
    { id: "conto_aperto", f: "persone",
      it: { n: "IL CONTO APERTO", q: "NEL TUO TURNO · SCEGLI UN GIOCATORE · IL TURNO CONTINUA",
            x: "Scegli un giocatore che non ha già un conto aperto: la prossima carta che pesca finisce nella tua mano invece che nella sua. Se pesca un buttafuori, il buttafuori arriva a te, e tocca a te salvarti col SANGUE FREDDO o con la MAZZETTA.",
            o: "È l’unico furto in cui chi ruba rischia. Giocalo su chi sta per pescare quando sai che in cima non c’è pericolo." },
      en: { n: "ON THE TAB", q: "ON YOUR TURN · PICK A PLAYER · YOUR TURN GOES ON",
            x: "Pick a player who does not already have a tab open: the next card they draw goes into your hand instead of theirs. If they draw a bouncer, the bouncer comes to you, and it is up to you to survive with COOL HAND or a BRIBE.",
            o: "The only steal where the thief takes the risk. Play it on someone about to draw when you know the top is safe." } },
    { id: "occhi_chiusi", f: "persone",
      it: { n: "A OCCHI CHIUSI", q: "NEL TUO TURNO · SCEGLI UN GIOCATORE · IL TURNO CONTINUA",
            x: "Scegli un giocatore: non vede più la sua mano finché non pesca e resta al tavolo. Al buio può solo pescare, calare un NON VALE e fare le scelte che gli toccano. Tutto il resto aspetta che torni la luce.",
            o: "Toglie a qualcuno le sue difese per un giro: niente RADDOPPIO, niente IMPILA. La MAZZETTA invece funziona anche al buio." },
      en: { n: "BLIND", q: "ON YOUR TURN · PICK A PLAYER · YOUR TURN GOES ON",
            x: "Pick a player: they cannot see their hand until they draw and stay at the table. In the dark they can only draw, drop a NO DICE, and make the choices that fall to them. Everything else waits for the lights to come back.",
            o: "Strips someone of their defences for a round: no DOUBLE DOWN, no STACK. The BRIBE still works in the dark." } },
    { id: "sangue_freddo", f: "persone",
      it: { n: "SANGUE FREDDO", q: "NON SI GIOCA · VALE FINCHÉ CE L’HAI IN MANO",
            x: "Nel mazzo ce n’è al massimo una. Finché è nella tua mano, quando peschi un buttafuori non esci: lo tieni in mano, e agli altri sembra una pescata qualunque. Vale per un buttafuori alla volta. Se qualcuno ti ruba il SANGUE FREDDO mentre tieni il buttafuori, sei fuori. Se ti rubano il buttafuori, passa a chi lo ha preso: si salva solo col suo SANGUE FREDDO o con una MAZZETTA.",
            o: "Scatta prima della MAZZETTA, così la mazzetta resta per la volta dopo. È un segreto: non farti rubare le carte." },
      en: { n: "COOL HAND", q: "NOT PLAYED · WORKS WHILE IT IS IN YOUR HAND",
            x: "There is at most one in the deck. While it is in your hand, drawing a bouncer does not put you out: you keep it in your hand, and to the others it looks like any other draw. It covers one bouncer at a time. If someone steals your COOL HAND while you hold the bouncer, you are out. If they steal the bouncer, it passes to whoever took it: they survive only with their own COOL HAND or a BRIBE.",
            o: "It kicks in before the BRIBE, so your bribe stays for next time. It is a secret: don’t let your cards get stolen." } },

    /* ── I GETTONI ────────────────────────────────────────────────── */
    { id: "tok_colosseo", f: "gettoni",
      it: { n: "COLOSSEO", q: "IN COPPIA O A TRIS · NEL TUO TURNO",
            x: "Da solo non fa niente. Due COLOSSEO: scegli un giocatore, vedi le sue carte coperte e ne prendi una. Tre COLOSSEO: guardi la sua mano e prendi la carta che vuoi. Il JOLLY vale come un COLOSSEO." },
      en: { n: "COLOSSEUM", q: "IN A PAIR OR THREE · ON YOUR TURN",
            x: "Does nothing alone. Two COLOSSEUM: pick a player, see their cards face down and take one. Three COLOSSEUM: look at their hand and take the card you want. A WILD CHIP counts as a COLOSSEUM." } },
    { id: "tok_ring", f: "gettoni",
      it: { n: "RING", q: "IN COPPIA O A TRIS · NEL TUO TURNO",
            x: "Da solo non fa niente. Due RING: prendi una sua carta coperta, scelta da te. Tre RING: guardi la mano e scegli. Il JOLLY vale come un RING." },
      en: { n: "THE RING", q: "IN A PAIR OR THREE · ON YOUR TURN",
            x: "Does nothing alone. Two RING: take one of their face-down cards, your pick. Three RING: look at the hand and choose. A WILD CHIP counts as a RING." } },
    { id: "tok_bandiera", f: "gettoni",
      it: { n: "BANDIERA", q: "IN COPPIA O A TRIS · NEL TUO TURNO",
            x: "Da solo non fa niente. Due BANDIERA: prendi una sua carta coperta, scelta da te. Tre BANDIERA: guardi la mano e scegli. Il JOLLY vale come una BANDIERA." },
      en: { n: "THE FLAG", q: "IN A PAIR OR THREE · ON YOUR TURN",
            x: "Does nothing alone. Two FLAG: take one of their face-down cards, your pick. Three FLAG: look at the hand and choose. A WILD CHIP counts as a FLAG." } },
    { id: "tok_citta", f: "gettoni",
      it: { n: "CITTÀ", q: "IN COPPIA O A TRIS · NEL TUO TURNO",
            x: "Da solo non fa niente. Due CITTÀ: prendi una sua carta coperta, scelta da te. Tre CITTÀ: guardi la mano e scegli. Il JOLLY vale come una CITTÀ." },
      en: { n: "THE CITY", q: "IN A PAIR OR THREE · ON YOUR TURN",
            x: "Does nothing alone. Two CITY: take one of their face-down cards, your pick. Three CITY: look at the hand and choose. A WILD CHIP counts as a CITY." } },
    { id: "tok_caveau", f: "gettoni",
      it: { n: "CAVEAU", q: "IN COPPIA O A TRIS · NEL TUO TURNO",
            x: "Da solo non fa niente. Due CAVEAU: prendi una sua carta coperta, scelta da te. Tre CAVEAU: guardi la mano e scegli. Il JOLLY vale come un CAVEAU." },
      en: { n: "THE VAULT", q: "IN A PAIR OR THREE · ON YOUR TURN",
            x: "Does nothing alone. Two VAULT: take one of their face-down cards, your pick. Three VAULT: look at the hand and choose. A WILD CHIP counts as a VAULT." } },
    { id: "jolly", f: "gettoni",
      it: { n: "JOLLY", q: "IN COPPIA O A TRIS · NEL TUO TURNO",
            x: "Vale come qualunque gettone quando fai una coppia o un tris. Anche due JOLLY insieme fanno una coppia. Da solo non fa niente.",
            o: "I furti coi gettoni non si fermano col NON VALE. Rubare un buttafuori è come pescarlo, e lo vedono tutti: ti salva il SANGUE FREDDO o la MAZZETTA, altrimenti sei fuori." },
      en: { n: "WILD CHIP", q: "IN A PAIR OR THREE · ON YOUR TURN",
            x: "Counts as any chip when you make a pair or a three. Two WILD CHIPS together also make a pair. Does nothing alone.",
            o: "Chip steals cannot be stopped with NO DICE. Stealing a bouncer counts as drawing it, in front of everyone: COOL HAND or a BRIBE saves you, otherwise you are out." } }
  ],

  /* LA PARTITA: [icona, titolo, testo] */
  partita: {
    it: [
      ["🎯", "LO SCOPO", "Non farti buttare fuori dal locale. Chi pesca un buttafuori esce. L’ultimo che resta seduto vince."],
      ["🃏", "L’INIZIO", "Da 2 a 7 al tavolo. Ognuno riceve 7 carte e una MAZZETTA. Il mazzo si costruisce sul numero di giocatori: dentro ci sono tanti buttafuori quanti siete meno uno."],
      ["🔄", "IL TUO TURNO", "Giochi quante carte vuoi, anche nessuna, una alla volta. Poi peschi dal mazzo: la pescata chiude il turno. Alcune carte chiudono il turno senza pescare, come PASSO, RADDOPPIO o CONTROMANO."],
      ["💀", "SE PESCHI IL BUTTAFUORI", "Ti salva il SANGUE FREDDO, se ce l’hai. Altrimenti la MAZZETTA: la spendi e rimetti il buttafuori nel mazzo dove vuoi. Senza nessuna delle due, sei fuori."],
      ["✋", "IL NON VALE", "Quando qualcuno gioca una carta, chi ha un NON VALE ha 3 secondi per annullarla, 5 se la carta colpiva lui. L’anello compare solo a chi può rispondere."],
      ["🪙", "I GETTONI", "Due gettoni uguali: vedi coperte le carte di chi vuoi e ne prendi una. Tre: guardi la sua mano scoperta e scegli. Il JOLLY vale come qualunque gettone."],
      ["🚪", "IL SEGNALINO ACCANTO AL MAZZO", "Il numero accanto ai tre buttafuori ti dice quanti ne sono ancora in gioco. Quando scende, un buttafuori ha appena fatto uscire qualcuno."],
      ["⏱️", "IL TEMPO", "Hai 30 secondi per turno. Se scadono peschi in automatico, e al terzo turno scaduto di fila sei fuori (in allenamento il tavolo ti aspetta). Nelle scelte, per esempio dove rimettere il buttafuori, a tempo scaduto si sceglie a caso."],
      ["🔒", "LA CHIUSURA DEL LOCALE", "Dopo 25 minuti di partita, 10 nei tornei, il locale chiude: tutte le carte del mazzo diventano buttafuori, e si esce uno dopo l’altro finché ne resta uno solo."],
      ["👆", "COME SI TOCCA", "Tocca una carta della mano per vederla grande, poi GIOCA. Per i gettoni: tocca un gettone, SCEGLI PER COMBINARE, poi l’altro, e scegli chi derubare. Tocca il mazzo o PESCA per pescare."]
    ],
    en: [
      ["🎯", "THE GOAL", "Don’t get thrown out of the bar. Whoever draws a bouncer is out. The last one still seated wins."],
      ["🃏", "THE START", "2 to 7 at the table. Everyone gets 7 cards and a BRIBE. The deck is built for the number of players: it holds one fewer bouncer than there are players."],
      ["🔄", "YOUR TURN", "Play as many cards as you like, even none, one at a time. Then draw from the deck: drawing ends your turn. Some cards end your turn without drawing, like CHECK, DOUBLE DOWN or WRONG WAY."],
      ["💀", "IF YOU DRAW THE BOUNCER", "COOL HAND saves you, if you have it. Otherwise the BRIBE: spend it and slide the bouncer back into the deck wherever you like. With neither, you are out."],
      ["✋", "NO DICE", "When someone plays a card, whoever holds a NO DICE has 3 seconds to cancel it, 5 if the card was aimed at them. The ring only shows up for those who can answer."],
      ["🪙", "THE CHIPS", "Two matching chips: see anyone’s cards face down and take one. Three: look at their open hand and choose. A WILD CHIP counts as any chip."],
      ["🚪", "THE COUNTER BY THE DECK", "The number next to the three bouncers tells you how many are still in play. When it drops, a bouncer just threw someone out."],
      ["⏱️", "THE CLOCK", "You have 30 seconds each turn. If it runs out you draw automatically, and on the third timed-out turn in a row you are out (in practice the table waits for you). In choices, like where to put the bouncer back, time out means a random pick."],
      ["🔒", "CLOSING TIME", "After 25 minutes of play, 10 in tournaments, the bar closes: every card in the deck becomes a bouncer, and players leave one after another until only one is left."],
      ["👆", "HOW TO TAP", "Tap a card in your hand to see it big, then PLAY. For chips: tap a chip, PICK TO COMBINE, then the other one, and choose who to rob. Tap the deck or DRAW to draw."]
    ]
  },

  /* SOLDI E TORNEI: [icona, titolo, testo] */
  soldi: {
    it: [
      ["🎟️", "LA POSTA", "Nelle lobby a soldi tutti mettono la stessa posta quando si siedono. Il tavolo parte quando è pieno: se non si riempie, a ognuno torna la sua posta."],
      ["🏆", "IL PIATTO", "Tutto a chi resta seduto per ultimo, tolto il 5% della casa. Nessun secondo posto."],
      ["🚶", "CHI SE NE VA", "Chi lascia il tavolo a metà partita non riprende la posta: il suo posto pesca in automatico, e al terzo turno scaduto è fuori."],
      ["🤖", "ALLENAMENTO", "ALLENATI ti mette al tavolo con 3 bot, gratis. I bot non giocano mai a soldi."],
      ["🏅", "NEI TORNEI", "Ogni tavolo manda avanti un solo giocatore, l’ultimo seduto. Il locale chiude a 10 minuti, quindi ogni partita finisce sempre con un vincitore."],
      ["🧯", "SE IL TAVOLO SI ROMPE", "Se una partita a soldi si interrompe per un guasto, a ognuno torna la sua posta."]
    ],
    en: [
      ["🎟️", "THE STAKE", "In paid lobbies everyone puts in the same stake when they sit down. The table starts when it is full: if it never fills, everyone gets their stake back."],
      ["🏆", "THE POT", "Everything goes to the last one seated, minus the house’s 5%. No second place."],
      ["🚶", "LEAVING", "Whoever leaves mid-game does not get their stake back: their seat draws automatically, and on the third timed-out turn it is out."],
      ["🤖", "PRACTICE", "PRACTICE sits you at a table with 3 bots, for free. Bots never play for money."],
      ["🏅", "IN TOURNAMENTS", "Each table sends exactly one player through, the last one seated. The bar closes at 10 minutes, so every game always ends with a winner."],
      ["🧯", "IF THE TABLE BREAKS", "If a paid game stops because of a fault, everyone gets their stake back."]
    ]
  }
};
if (typeof window !== "undefined") window.LC_ISTR = LC_ISTR;
